/**
 * Map a company name to a domain so we can fetch a real logo for it.
 * - `OVERRIDES` covers the cases auto-derivation gets wrong (acronyms, multi-word, NDA names, etc.).
 * - For everything else we strip parens/special chars, drop common suffixes, and append `.com`.
 * - When auto-derivation produces something we can't trust (no domain or too short), the
 *   `<CompanyLogo>` component falls back to the deterministic monogram.
 */

const OVERRIDES: Record<string, string> = {
  "ABG": "adityabirla.com",
  "AECOM": "aecom.com",
  "Accenture": "accenture.com",
  "Accenture India": "accenture.com",
  "Accenture Japan": "accenture.com",
  "Accordion": "accordion.com",
  "Accordian": "accordion.com",
  "accordion-Data engineering": "accordion.com",
  "Aditya Birla Group": "adityabirla.com",
  "Adobe": "adobe.com",
  "Alstom": "alstom.com",
  "Amazon": "amazon.com",
  "American Express (Amex)": "americanexpress.com",
  "Apple": "apple.com",
  "Atlas": "atlassian.com",
  "AuxaAI": "auxa.ai",
  "Auxia Software": "auxia.io",
  "Axis Bank": "axisbank.com",
  "Axtria": "axtria.com",
  "Axxela": "axxela.com",
  "Bajaj Auto": "bajajauto.com",
  "BlackBuck": "blackbuck.com",
  "BlackRock": "blackrock.com",
  "Bounteous x Accolite": "accolitedigital.com",
  "British Petrolium": "bp.com",
  "BrowserStack": "browserstack.com",
  "Capital One": "capitalone.com",
  "Cisco": "cisco.com",
  "ClearTrip": "cleartrip.com",
  "Cohesity": "cohesity.com",
  "Commonwealth Bank of Australia (CommBank)": "commbank.com.au",
  "Corridor Platform": "corridorplatforms.com",
  "Cosco": "costco.com",
  "Coupa": "coupa.com",
  "CynLr": "cynlr.com",
  "DE Shaw": "deshaw.com",
  "Deloitte": "deloitte.com",
  "Denso": "denso.com",
  "Deutsche Bank": "db.com",
  "Deutsche India Private Limited": "db.com",
  "DevRev": "devrev.ai",
  "Dezerv": "dezerv.in",
  "DP World": "dpworld.com",
  "Eaton": "eaton.com",
  "Electrowaves Electronics": "electrowaves.in",
  "EPAM": "epam.com",
  "Eternal": "eternal.com",
  "EXL": "exlservice.com",
  "Exxon Mobil": "exxonmobil.com",
  "Fanatics": "fanatics.com",
  "Finmechanics": "finmechanics.com",
  "Flipkart": "flipkart.com",
  "Future first": "futuresfirst.com",
  "Futures First": "futuresfirst.com",
  "GamesCraft": "gamescraft.com",
  "Google": "google.com",
  "HiLabs": "hilabs.com",
  "HMEL": "hmel.in",
  "Hindustan Unilever Ltd": "hul.co.in",
  "HSBC": "hsbc.com",
  "ICICI Bank": "icicibank.com",
  "ICICI Lombard": "icicilombard.com",
  "IDFC FIRST Bank": "idfcfirstbank.com",
  "Impact Analystics": "impactanalytics.co",
  "INCREFF": "increff.com",
  "Indus Insights": "indusinsights.com",
  "Info Edge": "infoedge.in",
  "Infosys": "infosys.com",
  "InMobi": "inmobi.com",
  "ION": "iongroup.com",
  "ixana": "ixana.ai",
  "Ivycap Ventures": "ivycap.in",
  "Jindal Steel": "jindalsteelpower.com",
  "JSW": "jsw.in",
  "Jupiter Money": "jupiter.money",
  "Juspay": "juspay.in",
  "Kantar": "kantar.com",
  "KKR & Co.": "kkr.com",
  "L&T": "larsentoubro.com",
  "Leap finance": "leapfinance.com",
  "LTIMindtree": "ltimindtree.com",
  "Lumber": "uselumber.com",
  "Mahindra Finance": "mahindrafinance.com",
  "MakeMyTrip": "makemytrip.com",
  "MAQ Software": "maqsoftware.com",
  "Mastercard": "mastercard.com",
  "Mathworks": "mathworks.com",
  "McKinsey": "mckinsey.com",
  "Media.net": "media.net",
  "Meesho": "meesho.com",
  "Merilytics": "merilytics.com",
  "Microsoft": "microsoft.com",
  "Mu Sigma": "mu-sigma.com",
  "Nexthop .AI": "nexthop.ai",
  "Nexus": "nexus.com",
  "NoBroker Technologies Solutions Pvt Ltd": "nobroker.in",
  "NopalCyber": "nopalcyber.com",
  "Nutanix": "nutanix.com",
  "NVIDIA": "nvidia.com",
  "NxtWave": "ccbp.in",
  "Okta": "okta.com",
  "Optum": "optum.com",
  "Oracle": "oracle.com",
  "Ozi": "ozi.com",
  "Pace Stock": "pacestock.com",
  "Paytm": "paytm.com",
  "PayU": "payu.in",
  "PhonePe": "phonepe.com",
  "Piramal": "piramal.com",
  "Porter": "porter.in",
  "Probo": "probo.in",
  "ProcDNA": "procdna.com",
  "Procol": "procol.io",
  "Protium Finance": "protium.co.in",
  "PW": "pw.live",
  "PWC": "pwc.com",
  "Public Sapient": "publicissapient.com",
  "Qualcomm": "qualcomm.com",
  "QuickSell": "quicksell.co",
  "Quince": "onequince.com",
  "RazorPay": "razorpay.com",
  "Reliance": "ril.com",
  "Rocol": "rocol.com",
  "Samsung R&D Noida": "samsung.com",
  "SAP LABS": "sap.com",
  "Schindler": "schindler.com",
  "Schlumberger": "slb.com",
  "Schneider": "se.com",
  "SEDEMAC": "sedemac.com",
  "Siemens Energy": "siemens-energy.com",
  "Sigmoid": "sigmoid.com",
  "Sirius AI": "siriusai.com",
  "SIXT": "sixt.com",
  "SLB": "slb.com",
  "Sprinklr": "sprinklr.com",
  "Squarepoint Capital": "squarepoint-capital.com",
  "Standard Chartered": "sc.com",
  "Tavant Technologies": "tavant.com",
  "TCE": "tce.co.in",
  "TCS": "tcs.com",
  "Tekion": "tekion.com",
  "Teradata": "teradata.com",
  "Tesla": "tesla.com",
  "Texas Instruments": "ti.com",
  "TMRW": "tmrw.in",
  "Tower Research Capital": "tower-research.com",
  "Tredence": "tredence.com",
  "Trilogy": "trilogy.com",
  "Uber": "uber.com",
  "UBS": "ubs.com",
  "UKG": "ukg.com",
  "Vikas Group": "vikasgroup.in",
  "Visa": "visa.com",
  "VVF": "vvfltd.com",
  "WarnerBros": "warnerbros.com",
  "Wells Fargo": "wellsfargo.com",
  "WEX": "wexinc.com",
  "Wex Fintech": "wexinc.com",
  "ZS Associates": "zs.com",
  "ZETA": "zeta.tech",
  "Zomato (Eternal)": "eternal.com",
  "Bajaj": "bajaj.com",
  "Indus insight -analyst": "indusinsights.com",
};

const STRIP_SUFFIX_RE =
  /\s+(india|japan|ltd|limited|pvt|private|technologies|technology|software|labs|systems|services|group|inc|corp|corporation|company|holdings)\b.*$/i;

function autoDomain(name: string): string | null {
  let cleaned = name.replace(/\([^)]*\)/g, " "); // drop paren content
  cleaned = cleaned.replace(STRIP_SUFFIX_RE, "");
  cleaned = cleaned.toLowerCase();
  cleaned = cleaned.replace(/&/g, " and ");
  cleaned = cleaned.replace(/[^a-z0-9\s]/g, "");
  const slug = cleaned.replace(/\s+/g, "");
  if (slug.length < 3) return null;
  return `${slug}.com`;
}

export function domainFor(name: string): string | null {
  if (OVERRIDES[name]) return OVERRIDES[name];
  // Try a case-insensitive override hit too
  const trimmed = name.trim();
  const ciKey = Object.keys(OVERRIDES).find((k) => k.toLowerCase() === trimmed.toLowerCase());
  if (ciKey) return OVERRIDES[ciKey];
  return autoDomain(trimmed);
}

export function logoUrl(domain: string, size: number = 128): string {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=${size}`;
}
